services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    ports:
      - ${NODE_RED_PORT}:1880
    restart: unless-stopped
    volumes:
      - nodered-data:/data
    env_file:
      - .env

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    user: '0'
    ports:
      - ${GF_PORT}:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    env_file:
      - .env

  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - ${DOCKER_INFLUXDB_PORT}:8086
    restart: unless-stopped
    volumes:
      - influx-data:/var/lib/influxdb2:rw
    env_file:
      - .env

  stream:
    build: ./stream
    container_name: stream
    ports:
      - ${STREAM_RTMP_PORT}:5000
    restart: unless-stopped
    env_file:
      - .env

volumes:
  nodered-data:
  grafana-data:
  influx-data:
