user nobody;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 768;
}

http {
    # Basic Settings
    sendfile on;
    tcp_nopush on;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Logging Settings
    access_log /var/log/nginx/access.log;

    # Gzip Settings
    gzip on;

    # Virtual Host Configs
    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;

    server {
        listen 80;
        server_name _;

        # Serve HTML video player
        location / {
            alias /usr/share/nginx/html/;
            index index.html;
        }

        # Serve stream
        location /hls/ {
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
            alias /tmp/hls/;
        }
    }
}

rtmp {
    server {
        listen 1935;
        application live {
            live on;
            record off;

            hls on;
            hls_path /tmp/hls/;
            hls_fragment 1s;
            hls_playlist_length 20s;
        }
    }
}
