erDiagram

    SENSOR_DATA {
        %% Metadata
        int experiment_id
        datetime timestamp
        %% Sensors
        float ambient_temperature
        float ambient_humidity
        float water_level
        float soil_temp
        float soil_humidity
        float ph
        float nitrogen
        float phosphorus
        float potassium
        float electric_conductivity
        float white_light
        float uv_light
        %% Actuators
        boolean fan_1
        boolean fan_2
        boolean pump
    }

    EXPERIMENT {
        int experiment_id
        int module_id
        string name
    }

    IMAGES {
        int experiment_id
        datetime timestamp
        string path
    }

    EXPERIMENT ||--o{ SENSOR_DATA : has
    EXPERIMENT ||--o{ IMAGES : has