erDiagram

    SENSOR_DATA {
        int experiment_id
        datetime timestamp
        float ambient_temperature
        float ambient_humidity
        float ambien_co2
        float soil_humidity
        float soil_temp
        float electric_conductivity
        float nitrogen
        float phosphorus
        float potassium
        float ph
        float white_light
        float uv_light
    }

    EXPERIMENT {
        int experiment_id
        int module_id
        string name
    }

    IMAGES {
        int experiment_id
        datetime timestamp
        string path
    }

    EXPERIMENT ||--o{ SENSOR_DATA : has
    EXPERIMENT ||--o{ IMAGES : has